# Copyright © 2021-2024 Geospatial Research Institute Toi Hangarau
# LICENSE: https://github.com/GeospatialResearch/Digital-Twins/blob/master/LICENSE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Definitions of services using local data_directory bind mounts for development use only.
# Merges with the primary `docker-compose.yml`
# Use with `docker compose -f docker-compose.yml docker-compose-dev.yml`
volumes:
  # Separate the database volume from the base services because this one will contain local file paths
  postgres_db_vol_dev:

services:
  db_postgres:
    volumes:
      - postgres_db_vol_dev:/var/lib/postgresql/data

  backend:
    volumes:
      - ${DATA_DIR_MODEL_OUTPUT}:/stored_data/model_output

  celery_worker:
    volumes:
      # Bind host data directories to container, allowing different instances to share data sources.
      - ${DATA_DIR}:/stored_data
      - ${DATA_DIR_MODEL_OUTPUT}:/stored_data/model_output
      - ${DATA_DIR_GEOSERVER}:/stored_data/geoserver

  geoserver:
    volumes:
      - ${DATA_DIR_GEOSERVER}:/opt/geoserver_data
