# syntax=docker/dockerfile:1
# Creates an image of both the src and tests folders and runs all unit tests
FROM python:3.8 as base
WORKDIR app/
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY db_configure.yml .
COPY src/ src/
COPY tests/ tests/

RUN pip install --no-cache-dir pytest

CMD ["python", "-m", "pytest"]
