# Copyright © 2021-2025 Geospatial Research Institute Toi Hangarau
# LICENSE: https://github.com/GeospatialResearch/Digital-Twins/blob/master/LICENSE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# YML file for setting up a reduced dev environment for WRF-Hydro work
# Locked down most package versions to reduce docker build time and keep in line with main environment.yml

name: smartidea
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11  # 11 for StrEnum
  - pip
  - python-dotenv==1.0.0
  - pandas==1.5.3
  - geopandas==0.12.2 # Needs to be explicit otherwise the dependencies required to use sjoin are not installed
  - rasterio==1.3.6 # Needs to be explicit as wheel fails to build if insalled as a dependency of geofabrics
  - pytest>=7.4.3
  - psycopg2==2.9.3 # Needed for Linux environments
  - botocore>=1.33.10 # Minimum version that is compatible with python >= 3.10 is botocore>=1.13.0
  - pip:
    - git+https://github.com/LukeParky/NewZeaLiDAR.git@v0.3

prefix:
